---

- name: Add module
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - ssl
    - suexec
    - include
    - fcgid

- name: Copy apache config ssl
  template:
    dest: "/etc/apache2/sites-available/sympa-ssl.conf"
    src: apache/sympa-ssl.conf.j2
    owner: root
    group: root
    mode: "0644"
  notify: sympa - Restart apache2

- name: Copy apache config ssl
  template:
    dest: "/etc/apache2/sites-available/{{ item.robot }}.conf"
    src: apache/sympa-robot-ssl.conf.j2
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ sympa_robots }}"
  notify: sympa - Restart apache2

- name: Remove default apache2 site.
  file:
    path: "{{ item }}"
    state: absent
  notify: sympa - Restart apache2
  with_items:
    - "/etc/apache2/sites-enabled/000-default.conf"
    - "/etc/apache2/sites-enabled/000-default-ssl*"

- name: Activate apache site.
  file:
    path: "/etc/apache2/sites-enabled/sympa-ssl.conf"
    src: "/etc/apache2/sites-available/sympa-ssl.conf"
    state: link
  notify: sympa - Restart apache2

- name: Activate apache site robots.
  file:
    path: "/etc/apache2/sites-enabled/{{ item.robot }}.conf"
    src: "/etc/apache2/sites-available/{{ item.robot }}.conf"
    state: link
  notify: sympa - Restart apache2
  with_items: "{{ sympa_robots }}"

- name: Copy apache config wwsympa
  template:
    dest: "/etc/apache2/conf-available/sympa.conf"
    src: apache/sympa.conf.j2
    owner: root
    group: root
    mode: "0600"
  notify: sympa - Restart apache2

- name: Activate apache conf.
  file:
    path: "/etc/apache2/conf-enabled/sympa.conf"
    src: "/etc/apache2/conf-available/sympa.conf"
    state: link
  notify: sympa - Restart apache2

- name: symbolic link to sympa
  file:
    path: "/var/www/sympa"
    src: "/usr/lib/cgi-bin/sympa"
    state: link
  notify: sympa - Restart apache2