---

- name: Install "debconf" and "debconf-utils" packages
  apt:
    name:
      - debconf
      - debconf-utils
    update_cache: yes
    cache_valid_time: 3600
    state: latest
    
- name: install PostgreSQL
  include: postgresql.yml
  when: sympa_db_restore and sympa_db_type == 'pgsql'

- name: install MySQL
  include: mysql.yml
  when: sympa_db_restore and sympa_db_type == 'mysql'


#- name: Add a 'sympa' group
#  group:
#    name: sympa
#    state: present

#- name: Create user sympa
#  user:
#    name: sympa
#    shell: /bin/bash
#    groups: sympa


#- name: Create mailname
#  template:
#    src: mailname.j2
#    dest: /etc/mailname
#    mode: 0600

#- name: Create sympa dir
#  file:
#    path: "{{ item }}"
#    state: directory
#  with_items:
#    - /etc/sympa
#    - /etc/mail
#    - /etc/sympa/sympa

#- name: Create sympa.conf
#  template:
#    src: sympa.conf.j2
#    dest: /etc/sympa/sympa/sympa.conf
#    mode: 0600
#  notify: Restart sympa

#####################################################
# Changes to fix a sympa package error in Debian 9  #

#- name: configure dpkg
#  template:
#    src: dpkg.cfg.j2
#    dest: "/etc/dpkg/dpkg.cfg"
#    owner: root
#    group: root
#    mode: 0644

#- name: Set sympa debconf keys' values
#  include_tasks: sympa_debconf.yml

- name: Definir opciones debconf de sympa
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop:
  - { name: 'sympa', question: 'wwsympa/webserver_type', value: '{{ sympa_webserver_type }}' , vtype: select }
  - { name: 'sympa', question: 'sympa/dbconfig-install', value: '{{ sympa_db_restore }}' , vtype: boolean }
  - { name: 'sympa', question: 'sympa/dbconfig-remove', value: '{{ sympa_db_restore }}' , vtype: boolean }
  - { name: 'sympa', question: 'sympa/language', value: '{{ sympa_lang }}', vtype: select }
  - { name: 'sympa', question: 'wwsympa/wwsympa_url', value: '{{ sympa_wwsympa_url }}', vtype: string }
  - { name: 'sympa', question: 'sympa/listmaster', value: '{{ sympa_listmaster | join(",") }}', vtype: string }
  - { name: 'sympa', question: 'sympa/hostname', value: '{{ sympa_hostname }}', vtype: string }
#  - { name: 'sympa', question: 'sympa/xxx', value: "true", vtype: boolean }

- name: Ver los valores debconf
  command: debconf-show sympa

- pause: 

- name: Install packages needed by sympa
  apt:
    name:
#      - dbconfig-mysql
      - dbconfig-pgsql
    update_cache: yes
    cache_valid_time: 3600
    state: latest


- name: Install sympa
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name: sympa
#  ignore_errors: yes

- name: Ver los valores debconf
  command: debconf-show sympa

- pause: 


#####################################################

- name: Install packages
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - postfix
      - fcgiwrap
      - apache2
      - perl
      - build-essential
      - libssl-dev
      - libmime-lite-html-perl
      - libapache2-mod-fcgid
      - cpanminus

- name: configure apache2
  include: apache2.yml

- name: Create robots dir
  file:
    path: "/etc/sympa/{{ item.robot }}"
    state: directory
  with_items: "{{ sympa_robots }}"

- name: Fix permissions
  file:
    path: "/etc/sympa"
    owner: sympa
    group: sympa
    recurse: yes

- name: Create auth.conf
  template:
    src: auth.conf.j2
    dest: /etc/sympa/auth.conf
    owner: sympa
    group: sympa
    mode: 0600
  notify: Restart sympa

- name: Create topics.conf
  template:
    src: topics.conf.j2
    dest: /etc/sympa/topics.conf
    owner: sympa
    group: sympa
    mode: 0600
  notify: Restart sympa

- name: Create topics robots
  template:
    src: topics.robot.conf.j2
    dest: /etc/sympa/{{ item.robot }}/topics.conf
    owner: sympa
    group: sympa
    mode: 0600
  when: item.topics is defined
  with_items: '{{ sympa_robots }}'
  notify: Restart sympa

- name: Create robots
  template:
    src: robot.conf.j2
    dest: "/etc/sympa/{{ item.robot }}/robot.conf"
    owner: sympa
    group: sympa
    mode: 0600
  when: sympa_robots
  with_items: '{{ sympa_robots }}'


- name: Create ldap_alias_manager.conf
  template:
    src: ldap_alias_manager.conf.j2
    dest: /etc/sympa/ldap_alias_manager.conf
    owner: sympa
    group: sympa
    mode: 0600
  when: sympa_ldap_alias_manager_conf is defined

- name: Create ldap_alias_entry.tt2
  copy:
    content: "{{ sympa_ldap_alias_entry }}"
    dest: /etc/sympa/ldap_alias_entry.tt2
    owner: sympa
    group: sympa
    mode: 0600
  when: sympa_ldap_alias_entry is defined

- name: Create folders for list templates
  file:
    path: "/etc/sympa/create_list_templates/{{ item.name }}"
    state: directory
    mode: 0750
    owner: sympa
    group: sympa
  loop: "{{ sympa_template_lists }}"
  when: sympa_template_lists is defined

- name: Create comment.tt2 for list templates
  copy:
    content: "{{ item.config }}"
    dest: "/etc/sympa/create_list_templates/{{ item.name }}/config.tt2"
    owner: sympa
    group: sympa
    mode: 0600
  loop: "{{ sympa_template_lists }}"
  when: sympa_template_lists is defined

- name: Create comment.tt2 for list templates
  copy:
    content: "{{ item.comment }}"
    dest: "/etc/sympa/create_list_templates/{{ item.name }}/comment.tt2"
    owner: sympa
    group: sympa
    mode: 0600
  loop: "{{ sympa_template_lists }}"
  when: sympa_template_lists is defined

- name: Disable default templates
  lineinfile:
    path: /usr/share/sympa/default/create_list.conf
    line: "{{ item }} hidden"
  when: not sympa_show_default_templates
  loop:
    - hotline
    - news-letter
    - confidential
    - discussion_list
    - html-news-letter
    - intranet_list
    - private_working_group
    - public_web_forum

- name: Enable default templates
  lineinfile:
    path: /usr/share/sympa/default/create_list.conf
    line: '{{ item }} hidden'
    state: absent
  when: sympa_show_default_templates
  loop:
    - hotline
    - news-letter
    - confidential
    - discussion_list
    - html-news-letter
    - intranet_list
    - private_working_group
    - public_web_forum

- name: Create datasources
  copy:
    content: "{{ item.content }}"
    dest: "/etc/sympa/data_sources/{{ item.name }}.incl"
    owner: sympa
    group: sympa
    mode: 0600
  loop: "{{ sympa_data_sources }}"
  when: sympa_data_sources is defined