---
## Configuration of a Sympa robot

- name: Create robot directory
  file:
    path: "/etc/sympa/{{ robot.domain }}"
    state: directory

- name: Create robot config file
  template:
    src: robot.conf.j2
    dest: "/etc/sympa/{{ robot.domain }}/robot.conf"
    owner: sympa
    group: sympa
    mode: 0600
  notify: Restart sympa


- name: Create robot topics file
  template:
    src: topics.robot.conf.j2
    dest: /etc/sympa/{{ robot.domain }}/topics.conf
    owner: sympa
    group: sympa
    mode: 0600
  when: robot.topics is defined

- name: Optional Apache robot configuration
  block:
  - name: Create Apache robot VirtualHost
    template:
      dest: "/etc/apache2/sites-available/{{ robot.domain }}.conf"
      src: apache/sympa-robot-vhost.conf.j2
      owner: root
      group: root
      mode: "0644"
    notify: sympa - Restart apache2

  - name: Activate Apache robot VirtualHost
    file:
      path: "/etc/apache2/sites-enabled/{{ robot.domain }}.conf"
      src: "../sites-available/{{ robot.domain }}.conf"
      state: link
    notify: sympa - Restart apache2
  when: sympa_apache2_configure
...
