---
## Sympa role handlers

- name: Restart sympa
  systemd:
    state: restarted
    name: sympa

- name: Reload sympa config
  become_user: sympa
  command: /usr/lib/sympa/bin/sympa.pl --reload_list_config

- name: sympa - Restart apache2
  service:
    name: apache2
    enabled: yes
    state: restarted

...
